deps.minecraft=26.1
deps.fabric_api=0.145.1+26.1

# Modrinth
deps.compatibleVersions=26.1-snapshot-7, 26.1-snapshot-8, 26.1-snapshot-9, 26.1-snapshot-10, 26.1-snapshot-11, 26.1-pre-1, 26.1-pre-2, 26.1-pre-3, 26.1-rc-1, 26.1-rc-2, 26.1-rc-3, 26.1, 26.1.1-rc-1, 26.1.1, 26.2-snapshot-1, 26.1.2-rc-1, 26.1.2
deps.compatibleLoaders=fabric